language: node_js
node_js:
  - 4.4.6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g gulp-cli<% if (filters.sass) { %>
  - gem install sass<% } %>
  - bower install
services: mongodb
