sudo: false
language: node_js
node_js:
  - 4.2.2
env:
  global:
    - SAUCE_USERNAME=fullstack_ci
    - SAUCE_ACCESS_KEY=1a527ca6-4aa5-4618-86ce-0278bf158cbf
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.0.0
before_install:
  - ./scripts/sauce_connect_setup.sh
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm install -g bower grunt-cli
services: mongodb
cache:
  directories:
    - node_modules
    - test/fixtures/node_modules
    - test/fixtures/bower_components
notifications:
  webhooks:
    urls:
      - secure: "DhPNqHXuUIeIGE9Ek3+63qhco+4MozXqMZL6dAKoq1MHQ2RAPO6SYIkUYZqDnuWYlwWao2EnTYcDREivIV/m/RnkP9bKlpX/n/RNJe+X4bwFaCU55fVKgkAFn3takSBC5SVoeTWHdWu3WhhqSdioWjT7mlE1wtt/RanSMb5Id8M="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
git:
  submodules: false
