language: node_js
node_js:
  - '0.12'
  - '4.0.0'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 4.0.0
before_script:
  - npm install -g bower grunt-cli<% if (filters.sass) { %>
  - gem install sass<% } %>
  - bower install
services: mongodb
